name: CI/CD Pipeline
on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install Cosign via go install
    steps:
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: main
     - name: Check install!
        run: cosign version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Scan for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: myapp:tag
          format: table

     - name: Setup Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "myapp"
          format: "table"
          output: "results-table.txt"

      - name: Check vulnerabilities
        run: |
          if [[ $(echo "${{ steps.vulnerabilities.outputs.vulnerabilities }}" | wc -l) -gt 1 ]]; then
            echo "Vulnerabilities found, exiting..."
            exit 1
          fi

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Get image digest
        id: get_digest
        run: echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest)"

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          DOCKER_USERNAME: ${{ secrets.vs1972}}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_REPOSITORY: ${{ secrets.COSIGN_REPOSITORY }