name: CI/CD Pipeline
on:
  push:
    branches:
      - 'main'
      - 'release/v[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    
  
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Scan for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action
        with:
          image-ref: myapp:tag
          format: table
          args: "--severity HIGH"
        id: vulnerabilities
