name: CI/CD Pipeline
on:
  push:
    branches:
      - 'main'
      - 'release/v[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
     
      - name: Scan go.mod file for vulnerabilities with Trivy
        run: |
          trivy filesystem --format table --vuln-type library --severity HIGH,CRITICAL "C:\Users\Vani\Desktop\MyCIC

     
