name: CI/CD Pipeline
on:
  push:
    branches:
      - 'main'
      - 'release/v[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: myapp:tag
          format: table
          args: "--severity HIGH"
        id: vulnerabilities

    
      
