name: CI/CD Pipeline
on:
  push:
    branches:
      - 'main'
      - 'release/v[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.51.3/trivy_0.51.3_Linux-64bit.tar.gz
          tar zxvf trivy_0.51.3_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          rm trivy_0.51.3_Linux-64bit.tar.gz
     
      - name: Scan go.mod file for vulnerabilities with Trivy
        run: |
          
          C:\path\to\trivy.exe filesystem --format table --vuln-type library --severity HIGH,CRITICAL "C:\Users\Vani\Desktop\MyCICDassignment\CICDassignment\go.mod"


      - name: Check vulnerabilities
        run: |
         
          if [[ $(echo "${{ steps.vulnerabilities.outputs.vulnerabilities }}" | grep "HIGH") ]]; then
          echo "Vulnerabilities found, exit"
          exit 1
          fi
          

    

      - name: SLACK_MESSAGE_ON_FAILURE
        if: steps.trivy.outcome == 'failure'
        uses : rtCamp/action-slack-notify@v2

        env:
          SLACK_CHANNEL: ${{ SECRETS.SLACK_CHANNEL_NAME}}
          SLACK_TOKEN: ${{ SECRETS.SLACK_TOKEN }}
          SLACK_TITLE: "* SCAN STATUS-FAILED-${{ SECRETS.SLACK_USERNAME}}*"
          SLACK_MESSAGE: 'TRIVY SCAN - VULNERABILITIES , REPORT UPLOADED'
          SLACK_USERNAME: ${{ SECRETS.SLACK_USERNAME}}
          SLACK_WEBHOOK: ${{ secrets.WEBHOOKURL }}
      - name: Slack upload scan report
        if: steps.trivy.outcome == 'failure'
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}  
          file_path: trivy_scan_results.txt
          initial_comment: 'Vulnerabilities found in Trivy scan'
      
      - name: vulnerabilities found- Exit workflow
        if: steps.trivy.outcome == 'failure'
        run: exit 1
  
  
     
            
        


